### ISSUE TITLE
Overwriting zone_id in file node.csv in grid2demand

### ISSUE THREAD

**Issue by asu-trans-ai-lab** [xyluo25/grid2demand#5]
When running grid2demand, the zone_id values in the node.csv file are overwritten incorrectly. Specifically, the package is overwriting the zone_id for all nodes, rather than limiting the update to activity nodes, which are defined as those nodes with a positive zone_id in the original file. These zone_id values are generated by osm2gmns, based on customized conditions for boundary or cross-layer nodes between two network layers.

This behavior does not align with the intended functionality of grid2demand, where only activity nodes should have a zone_id. As a result, downstream packages like path4gmns and DTALite cannot function properly due to the incorrect zone_id assignment.

Steps to Reproduce:

Load a network dataset into grid2demand.
Check the node.csv file for any zone-specific conditions (e.g., boundary or cross-layer nodes).
Verify the zone_id values assigned to all nodes after running grid2demand.
Examples:

For Sioux_Falls, the network dataset available at [node.csv](https://github.com/xyluo25/grid2demand/blob/main/datasets/demand_from_grid_use_zone_id_in_node/SF_demo/node.csv) contains:
8700 nodes, but only 300 activity nodes should have a zone_id.
For ASU Network, the dataset at [node.csv](https://github.com/xyluo25/grid2demand/blob/main/datasets/demand_from_grid_use_zone_id_in_node/ASU/auto/node.csv) has:
700 nodes, but only 70 activity nodes should have a zone_id.
After running grid2demand, all the nodes are assigned a zone_id, which is incorrect.

Expected Behavior:

Only activity nodes (nodes with a positive zone_id in the original file) should have their zone_id overwritten.
Non-activity nodes should not be assigned a zone_id.
Functional Impact:

The traffic assignment packages path4gmns and DTALite cannot operate properly with incorrect zone_id assignments for non-activity nodes.
Action Required:

Fix the issue in grid2demand so that only activity nodes have their zone_id values updated in node.csv.

**Comment by xyluo25** [comment]
fixed this with updated zone id in node.csv
